apiVersion: kubescheduler.config.k8s.io/v1beta3
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
clientConnection:
  kubeconfig: /Users/MYNAME/.kube/config
profiles:
  - schedulerName: kube-arch-scheduler
    plugins:
      filter:
        enabled:
          - name: "archfilter"
      score:
        enabled:
          - name: "archfilter"
    pluginConfig:
      - name: archfilter
        args:
          weight:
            amd64: 25
            arm64: 100
            arm: 75
            ppc64le: 0
            s390x: 0
            riscv64: 0
