apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
      lockObjectName: kube-arch-scheduler
      lockObjectNamespace: kube-system
    profiles:
    - schedulerName: kube-arch-scheduler
      plugins:
        filter:
          enabled:
          - name: "archfilter"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-arch-scheduler
  namespace: kube-system
  labels:
    component: kube-arch-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kube-arch-scheduler
  template:
    metadata:
      labels:
        component: kube-arch-scheduler
    spec:
      serviceAccount: kube-arch-scheduler-sa
      priorityClassName: system-cluster-critical
      volumes:
        - name: scheduler-config
          configMap:
            name: scheduler-config
      containers:
        - name: scheduler-ctrl
          image: ghcr.io/elementtech/kube-arch-scheduler:latest
          imagePullPolicy: IfNotPresent
          args:
            - kube-arch-scheduler
            - --config=/scheduler/scheduler-config.yaml
            - --v=3
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
          volumeMounts:
            - name: scheduler-config
              mountPath: /scheduler
