controllerManager:
  manager:
    image:
      repository: ghcr.io/jatalocks/kube-arch-scheduler
      tag: latest
    resources:
      requests:
        cpu: 0.5
        memory: 100Mi
  replicaCount: 1

# While enabled, this will add the scheduler to the default scheduler plugins,
# this will make it affect all pods in the cluster.
addToDefaultScheduler: true 

# If addToDefaultScheduler if false, this will be the name of the scheduler,
# and it will only affect pods with: [schedulerName: kube-arch-scheduler].
nonDefaultSchedulerName: kube-arch-scheduler