controllerManager:
  manager:
    image:
      repository: ghcr.io/elementtech/kube-arch-scheduler
      tag: latest
    resources:
      requests:
        cpu: 0.5
        memory: 100Mi
  replicaCount: 1

# While enabled, this will add the scheduler to the default scheduler plugins,
# this will make it affect all pods in the cluster.
addToDefaultScheduler: true

# If addToDefaultScheduler if false, this will be the name of the scheduler,
# and it will only affect pods with: [schedulerName: kube-arch-scheduler].
nonDefaultSchedulerName: kube-arch-scheduler

# dockerconfig.json is a base64 encoded docker config file, it will be used
# to pull the image manifests. The pod needs to have the secret mounted at
# /root/.docker/config.json. This is only needed if you are using a private
# registry. If you are using a public registry, you can leave this empty.
dockerConfigSecretName: ""

# The weight of each architecture,
# if a pod can sit on both, it will prefer the one with the higher weight.
# The default weight of undefined architectures is 0, meaning none will have
# any particular preference.
weight:
  amd64: 0
  arm64: 0
  arm: 0
  ppc64le: 0
  s390x: 0
  riscv64: 0
